### ISSUE TITLE
SSLError: read server hello A: tlsv1 unrecognized name - HTTPS resources

### ISSUE THREAD

**Issue by nibygro** [argos83/ritm#16]
Hi. I'm trying to use this gem, but when I'm trying to connect to `https://httpbin.org` from my ruby script usign local proxy (RITM) and ruby default `Net::HTTP` lib (with `use_ssl = true` and `VERIFY_NONE`) - it throws an error:

> #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 unrecognized name>

Ruby 2.4.1, RITM 1.0.0.

For Ruby 2.2 and 2.3 it works as expected :\

How I can fix it?

**Comment by argos83** [comment]
Hi @nibygro! I'll take a look at it and will get back to you

**Comment by argos83** [comment]
The cause of the error is https://bugs.ruby-lang.org/issues/13328 . I'll try to workaround it.

**Comment by argos83** [comment]
Released ritm v1.0.1 which includes the fix for this issue
