### ISSUE TITLE
Login on HTTPS loop

### ISSUE THREAD

**Issue by DSI666** [argos83/ritm#18]
Can't login on https resource (igram).

Getting Redirect Loop back into login page. Tested the same setup with burpProxy instead and I was able to login successfully. Both proxies didn't have their SSL certificates accepted, I just instructed the browser to ignore cert errors.

**Comment by argos83** [comment]
Thanks @DSI666 for the bug report. I'll try to reproduce it and get back to you

**Comment by argos83** [comment]
I was able to reproduce it. This is definitely a bug, somehow the request or response gets modified in some way that it alters the behaviour (and I can confirm that does not happen with burp).

**Comment by argos83** [comment]
This has been fixed in https://github.com/argos83/ritm/pull/22, and released as v1.0.2
